{"uid":"200480a685ef40b8","name":"test_update_userpwd_and_login[api-24]","fullName":"tests.endpoints.test_users#test_update_userpwd_and_login","historyId":"97b1ed844692423ef903ef178eb9d9c5","time":{"start":1733146067638,"stop":1733146069707,"duration":2069},"status":"failed","statusMessage":"AssertionError: Unable login with new credentials, status code: 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f23e8cf0b30>\nx_task_value = 'api-24'\n\n    @allure.feature(\"User API\")\n    @allure.story(\"Update user password\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-24\"])\n    def test_update_userpwd_and_login(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users = Users(**users_response.json())\n    \n        new_pass = f.password()\n        dto = UserBase(email=users.users[0].email, password=new_pass, name=f.name(), nickname=users.users[0].nickname)\n        dto.model_dump(exclude_none=True)\n        api_client.patch_user(dto, users.users[0].uuid, x_task_value)\n    \n        response = api_client.auth_user(dto, x_task_value)\n    \n>       assert response.status_code == 200, f\"Unable login with new credentials, status code: {response.status_code}\"\nE       AssertionError: Unable login with new credentials, status code: 404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\ntests/endpoints/test_users.py:121: AssertionError","flaky":true,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1733146055502,"stop":1733146055504,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1733146055504,"stop":1733146055504,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"worker_id","time":{"start":1733146055504,"stop":1733146055504,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_client","time":{"start":1733146055504,"stop":1733146055504,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"setup_test","time":{"start":1733146055505,"stop":1733146058069,"duration":2564},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Unable login with new credentials, status code: 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code","statusTrace":"api_client = <api_handler.api_client.ApiClient object at 0x7f23e8cf0b30>\nx_task_value = 'api-24'\n\n    @allure.feature(\"User API\")\n    @allure.story(\"Update user password\")\n    @pytest.mark.parametrize(\"x_task_value\", [\"api-24\"])\n    def test_update_userpwd_and_login(api_client, x_task_value):\n        users_response = api_client.get_users(x_task_value, 0)\n        users = Users(**users_response.json())\n    \n        new_pass = f.password()\n        dto = UserBase(email=users.users[0].email, password=new_pass, name=f.name(), nickname=users.users[0].nickname)\n        dto.model_dump(exclude_none=True)\n        api_client.patch_user(dto, users.users[0].uuid, x_task_value)\n    \n        response = api_client.auth_user(dto, x_task_value)\n    \n>       assert response.status_code == 200, f\"Unable login with new credentials, status code: {response.status_code}\"\nE       AssertionError: Unable login with new credentials, status code: 404\nE       assert 404 == 200\nE        +  where 404 = <Response [404]>.status_code\n\ntests/endpoints/test_users.py:121: AssertionError","steps":[],"attachments":[{"uid":"c7345a74a1d5ef01","name":"log","source":"c7345a74a1d5ef01.txt","type":"text/plain","size":2354},{"uid":"218472dd81da90e8","name":"stderr","source":"218472dd81da90e8.txt","type":"text/plain","size":2332}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"setup_test::0","time":{"start":1733146074608,"stop":1733146074608,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"story","value":"Update user password"},{"name":"feature","value":"User API"},{"name":"parentSuite","value":"tests.endpoints"},{"name":"suite","value":"test_users"},{"name":"host","value":"fv-az1272-97"},{"name":"thread","value":"2886-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.endpoints.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"x_task_value","value":"'api-24'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":3,"broken":1,"skipped":0,"passed":3,"unknown":0,"total":7},"items":[{"uid":"c106e661141c505d","reportUrl":"https://ils-808.github.io/qahack/99//#testresult/c106e661141c505d","status":"broken","statusDetails":"pydantic_core._pydantic_core.ValidationError: 2 validation errors for Users\nusers\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing\nmeta\n  Field required [type=missing, input_value={'code': 500, 'message': 'Internal server error'}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing","time":{"start":1733145946971,"stop":1733145947963,"duration":992}},{"uid":"2548a24c0fa31f9c","reportUrl":"https://ils-808.github.io/qahack/98//#testresult/2548a24c0fa31f9c","status":"passed","time":{"start":1733145786930,"stop":1733145788745,"duration":1815}},{"uid":"69cb54713e06748","reportUrl":"https://ils-808.github.io/qahack/63//#testresult/69cb54713e06748","status":"passed","time":{"start":1733086113656,"stop":1733086115484,"duration":1828}},{"uid":"dc306234b260bfdc","reportUrl":"https://ils-808.github.io/qahack/62//#testresult/dc306234b260bfdc","status":"failed","statusDetails":"AssertionError: Unable login with new credentials, status code: 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code","time":{"start":1733084994097,"stop":1733084995780,"duration":1683}},{"uid":"5a98d326fffd72d8","reportUrl":"https://ils-808.github.io/qahack/61//#testresult/5a98d326fffd72d8","status":"failed","statusDetails":"AssertionError: Unable login with new credentials, status code: 404\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code","time":{"start":1733084772637,"stop":1733084774238,"duration":1601}},{"uid":"85419e95bf4a0b49","reportUrl":"https://ils-808.github.io/qahack/60//#testresult/85419e95bf4a0b49","status":"passed","time":{"start":1733084493688,"stop":1733084495964,"duration":2276}}]},"tags":[]},"source":"200480a685ef40b8.json","parameterValues":["'api-24'"]}